name: ml-for-programmers
channels:
  - pytorch
  - conda-forge
  - mhoelzl
  - defaults
dependencies:
  - python>=3.8
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  # - tqdm
  # - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - seaborn
  # - altair
  # - yellowbrick
  # ML, STATS & DEEP LEARNING
  # - statsmodels
  - scikit-learn
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  - cudatoolkit=11.1
  - pytorch>=1.9
  - pytorch-model-summary
  - skorch
  - pillow=8.2
  # - fastbook
  # - tensorflow
  # - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  - openpyxl
  # APPLICATIONS
  - streamlit
  - pydantic
  - fastapi
  - nbex
  - pip:
     - -e .  # install git checkout of ml-for-programmers in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - black
  - ipykernel
  - jupyter
  # - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - rope
  - setuptools
  - rise
