name: ml-for-programmers
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
  - mhoelzl
dependencies:
  - cudatoolkit>=11
  - python>=3.8
  - pytorch>=1.7,<1.8
  - torchvision>=0.8,<0.9
  - pip
  - pip:
    - fastai>=2.2
    - fastapi
    - fastbook
    - graphviz
    - ipython
    - ipywidgets
    - matplotlib
    - nbdev>=0.2.12
    - nbex
    - numpy
    - pandas
    - pydantic
    - scikit_learn
    - scipy
    - seaborn
    - sentencepiece
    - streamlit
    - -e .  # install git checkout of ml-for-programmers in editable mode

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - black
  - ipykernel
  - jupyter
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - rope
  - setuptools
